services:
  postgres:
    image: postgres:15-alpine
    container_name: dojo_postgres
    environment:
      POSTGRES_DB: dojo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: